name: api_client
description: API Client package for OmaDhan
version: 0.0.1

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.3.3
