name: oma_dhan

packages:
  - .
  - packages/*

command:
  bootstrap:
    dependencies:
      cupertino_icons: ^1.0.6
      faker_dart: ^0.2.2
      flutter_bloc: ^8.1.6
      freezed_annotation: ^2.2.0
      drift: ^2.20.0
      drift_flutter: ^0.2.0
      uuid: ^4.5.0
      json_annotation: ^4.9.0
      firebase_core: ^3.6.0
      firebase_auth: ^5.3.1

    dev_dependencies:
      flutter_lints: ^4.0.0
      build_runner: ^2.3.3
      custom_lint: ^0.6.4
      drift_dev: ^2.20.1
      freezed: ^2.5.7
      json_serializable: ^6.8.0

    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    #
    # Source: https://github.com/firebase/flutterfire/blob/main/melos.yaml#L26
    runPubGetInParallel: false

    hooks:
      post: melos build

scripts:
  build:
    description: Run build runner build for all packages
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      failFast: true
      concurrency: 1

  watch:
    description: Run build runner watch for all packages
    run: dart run build_runner watch --delete-conflicting-outputs
    exec:
      failFast: true
      concurrency: 2 # The value should be the number of packages to be watched

  watch-authentication:
    description: Run build runner watch for authentication package
    run: dart run build_runner watch --delete-conflicting-outputs
    exec:
      failFast: true
    packageFilters:
      scope: 'authentication'

  create-bloc:
    description: Create files and directories for a new bloc and populate with boilerplate code. Provide --help for usage.
    run: $MELOS_ROOT_PATH/scripts/create-bloc.sh