// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0kAZUCguao08G0JAyG-uybdVne6wfNBE',
    appId: '1:431468570677:web:137b10ae5892b749ff697c',
    messagingSenderId: '431468570677',
    projectId: 'oma-dhan',
    authDomain: 'oma-dhan.firebaseapp.com',
    storageBucket: 'oma-dhan.appspot.com',
    measurementId: 'G-NE863Y2HH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJYNY0tooJ11RQsRX5Dxv-ng9FF4F7CLc',
    appId: '1:431468570677:android:a68fce7b8c833425ff697c',
    messagingSenderId: '431468570677',
    projectId: 'oma-dhan',
    storageBucket: 'oma-dhan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_x5GrgZ6JfQXfB5RDKAiXQldPjUElL8',
    appId: '1:431468570677:ios:e89a20058af519fdff697c',
    messagingSenderId: '431468570677',
    projectId: 'oma-dhan',
    storageBucket: 'oma-dhan.appspot.com',
    iosBundleId: 'com.omadhan.apps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_x5GrgZ6JfQXfB5RDKAiXQldPjUElL8',
    appId: '1:431468570677:ios:e89a20058af519fdff697c',
    messagingSenderId: '431468570677',
    projectId: 'oma-dhan',
    storageBucket: 'oma-dhan.appspot.com',
    iosBundleId: 'com.omadhan.apps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0kAZUCguao08G0JAyG-uybdVne6wfNBE',
    appId: '1:431468570677:web:b16c4081c90a3f2bff697c',
    messagingSenderId: '431468570677',
    projectId: 'oma-dhan',
    authDomain: 'oma-dhan.firebaseapp.com',
    storageBucket: 'oma-dhan.appspot.com',
    measurementId: 'G-V8E4HCXE7T',
  );
}
